import type {
  User,
  Product,
  Conversation,
  Message,
  Transaction,
} from './types';
import { CAMPUS_LOCATIONS } from './types';
import { SEED_IMAGES } from './seedImages';

// Seed data for first-run initialization. Fixed IDs so relations are stable.

export const SEED_USERS: User[] = [
  {
    id: 'seed-admin',
    email: 'admin@universite.edu.tr',
    fullName: 'Site Yöneticisi',
    department: 'İdari İşler',
    role: 'admin',
    isBanned: false,
    createdAt: '2025-01-01T09:00:00.000Z',
  },
  {
    id: 'seed-student-1',
    email: 'elif.yilmaz@boun.edu.tr',
    fullName: 'Elif Yılmaz',
    department: 'İktisat',
    role: 'student',
    isBanned: false,
    createdAt: '2025-02-03T10:30:00.000Z',
  },
  {
    id: 'seed-student-2',
    email: 'mehmet.demir@metu.edu.tr',
    fullName: 'Mehmet Demir',
    department: 'Elektrik Mühendisliği',
    role: 'student',
    isBanned: false,
    createdAt: '2025-02-10T14:15:00.000Z',
  },
  {
    id: 'seed-student-3',
    email: 'zeynep.kaya@bilkent.edu.tr',
    fullName: 'Zeynep Kaya',
    department: 'Psikoloji',
    role: 'student',
    isBanned: false,
    createdAt: '2025-03-01T08:45:00.000Z',
  },
];

const now = '2025-03-15T12:00:00.000Z';

export const SEED_PRODUCTS: Product[] = [
  // Etek
  {
    id: 'seed-prod-1',
    sellerId: 'seed-student-1',
    title: 'Siyah Pliseli Etek',
    description: 'Bir kere giyildi, leke yok. çok şık duruyor. Kampüste elden teslim.',
    price: 120,
    category: 'Etek',
    size: 'S',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[0],
    status: 'active',
    images: [SEED_IMAGES.etek1],
    createdAt: now,
  },
  {
    id: 'seed-prod-2',
    sellerId: 'seed-student-3',
    title: 'Ekru Mini Etek',
    description: 'Yazlık, koton kumaş. Temiz ve ütülü.',
    price: 75,
    category: 'Etek',
    size: 'M',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[1],
    status: 'active',
    images: [SEED_IMAGES.etek2],
    createdAt: now,
  },
  // Elbise
  {
    id: 'seed-prod-3',
    sellerId: 'seed-student-1',
    title: 'Çiçekli Yazlık Elbise',
    description: 'Zara\'dan, bir kez giyildi. çok rahat ve hafif.',
    price: 180,
    category: 'Elbise',
    size: 'M',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[2],
    status: 'active',
    images: [SEED_IMAGES.elbise1],
    createdAt: now,
  },
  {
    id: 'seed-prod-4',
    sellerId: 'seed-student-3',
    title: 'Siyah Elbise — Davetlik',
    description: 'Mezuniyet töreni için alındı, bir kez giyildi. çok şık.',
    price: 250,
    category: 'Elbise',
    size: 'S',
    condition: 'Sıfır',
    meetupLocation: CAMPUS_LOCATIONS[3],
    status: 'active',
    images: [SEED_IMAGES.elbise2],
    createdAt: now,
  },
  // Pantolon
  {
    id: 'seed-prod-5',
    sellerId: 'seed-student-2',
    title: 'Slim Fit Kot Pantolon',
    description: 'Mavi renk, dar kalıp. Az kullanıldı, yıpranma yok.',
    price: 140,
    category: 'Pantolon',
    size: 'M',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[0],
    status: 'active',
    images: [SEED_IMAGES.pantolon1],
    createdAt: now,
  },
  {
    id: 'seed-prod-6',
    sellerId: 'seed-student-1',
    title: 'Kargo Pantolon — Haki',
    description: 'Bol kesim, çok cepli. Kampüs için ideal.',
    price: 95,
    category: 'Pantolon',
    size: 'L',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[1],
    status: 'active',
    images: [SEED_IMAGES.pantolon2],
    createdAt: now,
  },
  // Gömlek
  {
    id: 'seed-prod-7',
    sellerId: 'seed-student-2',
    title: 'Beyaz Oxford Gömlek',
    description: 'Klasik kesim, üniversite için ideal. çok temiz.',
    price: 110,
    category: 'Gömlek',
    size: 'M',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[2],
    status: 'active',
    images: [SEED_IMAGES.gomlek1],
    createdAt: now,
  },
  {
    id: 'seed-prod-8',
    sellerId: 'seed-student-1',
    title: 'Lacivert Çizgili Gömlek',
    description: 'Casual, rahat kumaş. Bir kez yıkandı.',
    price: 85,
    category: 'Gömlek',
    size: 'L',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[3],
    status: 'active',
    images: [SEED_IMAGES.gomlek2],
    createdAt: now,
  },
  // Kaban
  {
    id: 'seed-prod-9',
    sellerId: 'seed-student-1',
    title: 'Vintage Yün Kaban',
    description: 'Bir kere giyildi, çok sıcak tutuyor. Kaliteli yün, kolları uzun.',
    price: 450,
    category: 'Kaban',
    size: 'M',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[0],
    status: 'active',
    images: [SEED_IMAGES.kaban1],
    createdAt: now,
  },
  {
    id: 'seed-prod-10',
    sellerId: 'seed-student-3',
    title: 'Bej Uzun Kaban',
    description: 'Kışlık, kapüşonlu. çok az giyildi, yıkandı.',
    price: 320,
    category: 'Kaban',
    size: 'S',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[4],
    status: 'active',
    images: [SEED_IMAGES.kaban2],
    createdAt: now,
  },
  // Mont
  {
    id: 'seed-prod-11',
    sellerId: 'seed-student-3',
    title: 'Spor Mont — Rüzgârlık',
    description: 'Koşu için, çok hafif. Beden S.',
    price: 90,
    category: 'Mont',
    size: 'S',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[4],
    status: 'active',
    images: [SEED_IMAGES.mont1],
    createdAt: now,
  },
  {
    id: 'seed-prod-12',
    sellerId: 'seed-student-2',
    title: 'Şişme Mont — Siyah',
    description: 'Kış için, çok sıcak. içi tüy, dışı su geçirmez.',
    price: 200,
    category: 'Mont',
    size: 'L',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[0],
    status: 'active',
    images: [SEED_IMAGES.mont2],
    createdAt: now,
  },
  // Kazak
  {
    id: 'seed-prod-13',
    sellerId: 'seed-student-1',
    title: 'Krem Triko Kazak',
    description: 'Yumuşacık, kış için birebir. hiç bozulmadı.',
    price: 100,
    category: 'Kazak',
    size: 'M',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[1],
    status: 'active',
    images: [SEED_IMAGES.kazak1],
    createdAt: now,
  },
  {
    id: 'seed-prod-14',
    sellerId: 'seed-student-3',
    title: 'Lacivert Balıkçı Kazak',
    description: 'Klasik, her şeyle uyumlu. bir kez giyildi.',
    price: 80,
    category: 'Kazak',
    size: 'S',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[2],
    status: 'active',
    images: [SEED_IMAGES.kazak2],
    createdAt: now,
  },
  // Tişört
  {
    id: 'seed-prod-15',
    sellerId: 'seed-student-2',
    title: 'Beyaz Basic Tişört',
    description: 'Pamuklu, çok rahat. iki adet var, ikisi de satılık.',
    price: 35,
    category: 'Tişört',
    size: 'M',
    condition: 'Sıfır',
    meetupLocation: CAMPUS_LOCATIONS[3],
    status: 'active',
    images: [SEED_IMAGES.tisort1],
    createdAt: now,
  },
  {
    id: 'seed-prod-16',
    sellerId: 'seed-student-1',
    title: 'Baskılı Tişört — Vintage',
    description: 'Grup tişörtü, çok az giyildi. baskı sağlam.',
    price: 50,
    category: 'Tişört',
    size: 'L',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[4],
    status: 'active',
    images: [SEED_IMAGES.tisort2],
    createdAt: now,
  },
  // Bluz
  {
    id: 'seed-prod-17',
    sellerId: 'seed-student-3',
    title: 'Saten Bluz — Pudra',
    description: 'Davet için, çok şık. düğmeli, boyu normal.',
    price: 130,
    category: 'Bluz',
    size: 'S',
    condition: 'Sıfır',
    meetupLocation: CAMPUS_LOCATIONS[0],
    status: 'active',
    images: [SEED_IMAGES.bluz1],
    createdAt: now,
  },
  {
    id: 'seed-prod-18',
    sellerId: 'seed-student-1',
    title: 'Volanlı Bluz — Beyaz',
    description: 'Yazlık, çok hafif. bir kez giyildi, yıkandı.',
    price: 70,
    category: 'Bluz',
    size: 'M',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[1],
    status: 'active',
    images: [SEED_IMAGES.bluz2],
    createdAt: now,
  },
  // Eşofman
  {
    id: 'seed-prod-19',
    sellerId: 'seed-student-2',
    title: 'Gri Eşofman Altı',
    description: 'Bol kesim, çok rahat. kampüste giymelik.',
    price: 60,
    category: 'Eşofman',
    size: 'L',
    condition: 'İyi',
    meetupLocation: CAMPUS_LOCATIONS[2],
    status: 'active',
    images: [SEED_IMAGES.esofman1],
    createdAt: now,
  },
  {
    id: 'seed-prod-20',
    sellerId: 'seed-student-3',
    title: 'Siyah Eşofman Takım',
    description: 'Üst ve alt birlikte. az kullanıldı, tüylenme yok.',
    price: 150,
    category: 'Eşofman',
    size: 'M',
    condition: 'Az Kullanılmış',
    meetupLocation: CAMPUS_LOCATIONS[3],
    status: 'active',
    images: [SEED_IMAGES.esofman2],
    createdAt: now,
  },
];

export const SEED_CONVERSATIONS: Conversation[] = [];
export const SEED_MESSAGES: Message[] = [];
export const SEED_TRANSACTIONS: Transaction[] = [];
